# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import realsenseservice_pb2 as realsenseservice__pb2


class RealSenseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.unary_stream(
                '/RealSense.RealSense/StreamVideo',
                request_serializer=realsenseservice__pb2.RequestVideo.SerializeToString,
                response_deserializer=realsenseservice__pb2.RealSenseVideoFrame.FromString,
                )


class RealSenseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealSenseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=realsenseservice__pb2.RequestVideo.FromString,
                    response_serializer=realsenseservice__pb2.RealSenseVideoFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RealSense.RealSense', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RealSense(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/RealSense.RealSense/StreamVideo',
            realsenseservice__pb2.RequestVideo.SerializeToString,
            realsenseservice__pb2.RealSenseVideoFrame.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
